const host = "http://localhost:4000";
export const RegisterRoute = `${host}/api/auth/register`;
export const LoginRoute = `${host}/api/auth/login`;
export const SetAvatarRoute = `${host}/api/auth/setAvatar`;
export const GetAllUsers = `${host}/api/auth/getAllUsers`;
export const AddMessages = `${host}/api/chat/add-message`;
export const GetMessages = `${host}/api/chat/get-messages`;
export const GetAllFriends = `${host}/api/auth/get-friends`;
export const UpdateUserProfile = `${host}/api/auth/update-user-profile`;
